In [1]:
%autosave 3

Autosaving every 3 seconds


<a id='0'></a>

### 目录
* [numpy](#1)
* [pandas](#2)
* [matplotlib](#3)

<a id='1'></a>

# [numpy](#0)
严格说

np.matmul(a, b)
完全等价于

a @ b
只是表示方式不同。



对于矩阵乘法来说，

np.matmul(a, b)
也完全等价于

np.dot(a, b)


np.random.seed(42)
生成随机数[0,1)

### shape


In [ ]:
>>> c = array([[1,1],[1,2],[1,3],[1,4]])  
 c.shape  
(4, 2)  
>>> c.shape[0]  
4  
>>> c.shape[1]  
2  

In [1]:
 import numpy as np

In [2]:
# 查看版本
print(np.__version__)

1.14.0


In [4]:
np.linspace(10,60,num=6)

array([10., 20., 30., 40., 50., 60.])

In [ ]:
np.dot(A, B)
# 如果使用 np.mat 将二维数组准确定义为矩阵，就可以直接使用 * 完成矩阵乘法计算
np.mat(A) * np.mat(B)

In [7]:
a = np.random.randint(10, size = (3,4))
a


array([[6, 8, 8, 8],
       [7, 1, 4, 1],
       [9, 2, 8, 3]])

In [9]:
np.hsplit(a,4)

[array([[6],
        [7],
        [9]]), array([[8],
        [1],
        [2]]), array([[8],
        [4],
        [8]]), array([[8],
        [1],
        [3]])]

In [10]:
np.vsplit(a,3)

[array([[6, 8, 8, 8]]), array([[7, 1, 4, 1]]), array([[9, 2, 8, 3]])]

In [11]:
a = np.array(([1,4,3],
             [6,2,9],
             [4,7,2]))
a

array([[1, 4, 3],
       [6, 2, 9],
       [4, 7, 2]])

<a id='2'></a>
# [pandas](#0)



### get_dummies
是将拥有不同值的变量转换为0/1数值 进行one-hot编码

In [1]:
import tensorflow as tf

hello = tf.constant('Hello, TensorFlow!')

sess = tf.Session()

sess.run(hello)

C:\Users\lee\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


b'Hello, TensorFlow!'

<a id=3></a>
# [mtplotlib](#0)

In [1]:
from keras.datasets import fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

C:\Users\lee\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


4423680/4422102 [==============================] - 7s 1us/step


In [3]:
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

KeyboardInterrupt: 

In [4]:
from keras.datasets import boston_housing

(x_train, y_train), (x_test, y_test) = boston_housing.load_data()

KeyboardInterrupt: 

In [5]:
from keras.datasets import fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

In [ ]:
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()